service:
  name: filmweb-scratcher

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getFilm:
    handler: src/appRoutes.getFilm
    environment:
      FILMWEB_SEARCH_URI: http://www.filmweb.pl/films/search
    events:
      - http:
          method: get
          path: films
          cors: true
          request:
            parameters:
              querystrings:
                title: true
